version: "3"
services:
  app:
    image: test:latest
    build: .
    ports:
      - "12222:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: oauth
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306