spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
---
spring:
  profiles: default
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/testoauth?createDatabaseIfNotExist=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  profiles: docker
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver